"use strict";

const path = require("path");
const isLocal = typeof process.pkg === "undefined";
const basePath = isLocal ? process.cwd() : path.dirname(process.execPath);
const { MODE } = require(path.join(basePath, "src/blendMode.js"));

//const buildDir = path.join(basePath, "/build");
//const layersDir = path.join(basePath, "/layers");
const buildDir = "../build";
const layersDir = "../layers";

const description =
  "A Collection of 10,000 algorithmically generated nfts that express the underlying aspcted of the metaverse";
const baseUri = "ipfs://NewUriToReplace";

const outputJPEG = false; // if false, the generator outputs png's
/**
 * Set your tokenID index start number.
 * ⚠️ Be sure it matches your smart contract!
 */
const startIndex = 1;

// if you use an empty/transparent file, set the name here.
const emptyLayerName = "NONE";

//IF you need a provenance hash, turn this on
const hashImages = true;

const layerConfigurations = [
  {
    growEditionSizeTo: 200,
    namePrefix: "Astral Traveler", // Use to add a name to Metadata `name:`
    layersOrder: [
      {
        name: "Background",
        options: {
          bypassDNA: false,
        },
      },
      { name: "Base Character" },
      { name: "Tattoo" },
      { name: "Clothes" },
      {
        name: "Expression",
        options: {
          bypassDNA: false,
        },
      },
      { name: "Eyes" },
      { name: "Necklace" },
      { name: "Hair" },
      { name: "Earings" },
      { name: "Beard" },
      { name: "Headware" },
      { name: "Sneakers" },
    ],
  },
  // {
  //   growEditionSizeTo: 10,
  //   namePrefix: "Lion",
  //   resetNameIndex: true, // this will start the Lion count at #1 instead of #6
  //   layersOrder: [
  //     { name: "Background" },
  //     { name: "Hats" },
  //     { name: "Male Hair" },
  //   ],
  // },
];

/**
 * Incompatible items can be added to this object by a files cleanName
 * This works in layer order, meaning, you need to define the layer that comes
 * first as the Key, and the incompatible items that _may_ come after.
 * The current version requires all layers to have unique names, or you may
 * accidentally set incompatibilities for the _wrong_ item.
 */
const incompatible = {
  "Copper Rock": [
    "Black Helix",
    "Gold Helix",
    "Black Loop",
    "Black Stud",
    "Double Black Stud",
    "Double Gold Stud",
    "Gold Ring",
    "Gold Stud",
  ],
  "Indigo Rock": [
    "Black Helix",
    "Gold Helix",
    "Black Loop",
    "Black Stud",
    "Double Black Stud",
    "Double Gold Stud",
    "Gold Ring",
    "Gold Stud",
  ],
  "Pink Rock": [
    "Black Helix",
    "Gold Helix",
    "Black Loop",
    "Black Stud",
    "Double Black Stud",
    "Double Gold Stud",
    "Gold Ring",
    "Gold Stud",
  ],
  "Purple Rock": [
    "Black Helix",
    "Gold Helix",
    "Black Loop",
    "Black Stud",
    "Double Black Stud",
    "Double Gold Stud",
    "Gold Ring",
    "Gold Stud",
  ],
  "Sun Set Rock": [
    "Black Helix",
    "Gold Helix",
    "Black Loop",
    "Black Stud",
    "Double Black Stud",
    "Double Gold Stud",
    "Gold Ring",
    "Gold Stud",
  ],
  Aqua: ["Blangkon", "Indigenous"],
  Tan: ["Blangkon", "Indigenous"],
  Olive: ["Blangkon", "Indigenous"],
  Fair: ["Blangkon", "Indigenous"],
  Bronze: ["Blangkon", "Indigenous"],
  Copper: ["Blangkon", "Indigenous"],
  Brown: ["Blangkon", "Indigenous"],
  Charcoal: ["Blangkon", "Indigenous"],
  Diamond: ["Blangkon", "Indigenous"],
  Ebony: ["Blangkon", "Indigenous"],
  Glitch: ["Blangkon", "Indigenous"],
  Gold: ["Blangkon", "Indigenous"],
  Graphite: ["Blangkon", "Indigenous"],
  Gray: ["Blangkon", "Indigenous"],
  Ivory: ["Blangkon", "Indigenous"],
  Onyx: ["Blangkon", "Indigenous"],
  Sapphire: ["Blangkon", "Indigenous"],
  Spectrum: ["Blangkon", "Indigenous"],

  "Black Hoddie": [
    "Maelstrom",
    "Rock Maelstrom",
    "Emo Maelstrom",
    "Emo Jester",
    "Rock Jester",
    "Prince of Chaos",
    "The Ace of Knaves",
    "Helmet Blue",
    "Helmet Indigo",
  ],
  Blangkon: [
    "Maelstrom",
    "Rock Maelstrom",
    "Emo Maelstrom",
    "Emo Jester",
    "Rock Jester",
    "Prince of Chaos",
    "The Ace of Knaves",
    "Helmet Blue",
    "Helmet Indigo",
  ],
  "Casual Blue Gold Crimson": [
    "Maelstrom",
    "Rock Maelstrom",
    "Emo Maelstrom",
    "Emo Jester",
    "Rock Jester",
    "Prince of Chaos",
    "The Ace of Knaves",
    "Helmet Blue",
    "Helmet Indigo",
  ],
  "Casual Blue Gold": [
    "Maelstrom",
    "Rock Maelstrom",
    "Emo Maelstrom",
    "Emo Jester",
    "Rock Jester",
    "Prince of Chaos",
    "The Ace of Knaves",
    "Helmet Blue",
    "Helmet Indigo",
  ],
  "Casual Blue Gray": [
    "Maelstrom",
    "Rock Maelstrom",
    "Emo Maelstrom",
    "Emo Jester",
    "Rock Jester",
    "Prince of Chaos",
    "The Ace of Knaves",
    "Helmet Blue",
    "Helmet Indigo",
  ],
  "Casual Blue Peach": [
    "Maelstrom",
    "Rock Maelstrom",
    "Emo Maelstrom",
    "Emo Jester",
    "Rock Jester",
    "Prince of Chaos",
    "The Ace of Knaves",
    "Helmet Blue",
    "Helmet Indigo",
  ],
  "Casual Blue": [
    "Maelstrom",
    "Rock Maelstrom",
    "Emo Maelstrom",
    "Emo Jester",
    "Rock Jester",
    "Prince of Chaos",
    "The Ace of Knaves",
    "Helmet Blue",
    "Helmet Indigo",
  ],
  "Casual Dark Blue": [
    "Maelstrom",
    "Rock Maelstrom",
    "Emo Maelstrom",
    "Emo Jester",
    "Rock Jester",
    "Prince of Chaos",
    "The Ace of Knaves",
    "Helmet Blue",
    "Helmet Indigo",
  ],
  "Green Hoddie": [
    "Maelstrom",
    "Rock Maelstrom",
    "Emo Maelstrom",
    "Emo Jester",
    "Rock Jester",
    "Prince of Chaos",
    "The Ace of Knaves",
    "Helmet Blue",
    "Helmet Indigo",
  ],
  Indigenous: [
    "Maelstrom",
    "Rock Maelstrom",
    "Emo Maelstrom",
    "Emo Jester",
    "Rock Jester",
    "Prince of Chaos",
    "The Ace of Knaves",
    "Helmet Blue",
    "Helmet Indigo",
  ],
  "Magenta Hoodie": [
    "Maelstrom",
    "Rock Maelstrom",
    "Emo Maelstrom",
    "Emo Jester",
    "Rock Jester",
    "Prince of Chaos",
    "The Ace of Knaves",
    "Helmet Blue",
    "Helmet Indigo",
  ],
  "Maroon Hoodie": [
    "Maelstrom",
    "Rock Maelstrom",
    "Emo Maelstrom",
    "Emo Jester",
    "Rock Jester",
    "Prince of Chaos",
    "The Ace of Knaves",
    "Helmet Blue",
    "Helmet Indigo",
  ],
  "Purple Hoodie": [
    "Maelstrom",
    "Rock Maelstrom",
    "Emo Maelstrom",
    "Emo Jester",
    "Rock Jester",
    "Prince of Chaos",
    "The Ace of Knaves",
    "Helmet Blue",
    "Helmet Indigo",
  ],
  "Relaxed Blue": [
    "Maelstrom",
    "Rock Maelstrom",
    "Emo Maelstrom",
    "Emo Jester",
    "Rock Jester",
    "Prince of Chaos",
    "The Ace of Knaves",
    "Helmet Blue",
    "Helmet Indigo",
  ],
  "Relaxed Orange": [
    "Maelstrom",
    "Rock Maelstrom",
    "Emo Maelstrom",
    "Emo Jester",
    "Rock Jester",
    "Prince of Chaos",
    "The Ace of Knaves",
    "Helmet Blue",
    "Helmet Indigo",
  ],
  "Traditional Blue": [
    "Maelstrom",
    "Rock Maelstrom",
    "Emo Maelstrom",
    "Emo Jester",
    "Rock Jester",
    "Prince of Chaos",
    "The Ace of Knaves",
    "Helmet Blue",
    "Helmet Indigo",
  ],
  "Traditional Crimson": [
    "Maelstrom",
    "Rock Maelstrom",
    "Emo Maelstrom",
    "Emo Jester",
    "Rock Jester",
    "Prince of Chaos",
    "The Ace of Knaves",
    "Helmet Blue",
    "Helmet Indigo",
  ],
  "Traditional Magenta": [
    "Maelstrom",
    "Rock Maelstrom",
    "Emo Maelstrom",
    "Emo Jester",
    "Rock Jester",
    "Prince of Chaos",
    "The Ace of Knaves",
    "Helmet Blue",
    "Helmet Indigo",
  ],
  "Traditional Orange": [
    "Maelstrom",
    "Rock Maelstrom",
    "Emo Maelstrom",
    "Emo Jester",
    "Rock Jester",
    "Prince of Chaos",
    "The Ace of Knaves",
    "Helmet Blue",
    "Helmet Indigo",
  ],
  Jester: [
    "Aqua Punk",
    "Auburn Afro",
    "Auburn Rock",
    "Gold Punk",
    "Bald",
    "Gray Emo ",
    "Black Afro",
    "Indigo Emo",
    "Black Beard",
    "Indigo Rock",
    "Black Brown Afro",
    "Jade Afro",
    "Black Dreadlocks Silver Beads",
    "Light Emo",
    "Black Natural Afro",
    "Black and Brown Afro",
    "Magenta Flame",
    "Blue Emo",
    "Magenta Punk",
    "Maelstrom",
    "Emo Maelstrom",
    "Rock Maelstrom",
    "Blue Flame Mohawk",
    "Maroon Afro",
    "Blue Knot",
    "Mop Top",
    "Blue Low Cut",
    "Neon Emo",
    "Pink Rock",
    "Brown Dreadlocks",
    "Purple Rock",
    "Brown Low Cut",
    "Rasta Gold",
    "Rasta Red",
    "Red Flame Mohawk",
    "Cooper Natural Afro",
    "Red Knot",
    "Copper Dreadlocks",
    "Red Punk",
    "Copper Rock",
    "Red Shadow Punk",
    "Dark Red Punk",
    "Redish Knot",
    "Dark Shag ",
    "Rasta Spectrum",
    "Rasta Black and Gold",
    "Saphire Flame Mohawk",
    "Rasta Auburn and Gold",
    "Rasta Black and Gold",
    "Rasta Black and Silver Beads",
    "Rasta Black and Spectrum",
    "Rasta Brown and  Silver",
    "Rasta Brown and Gold",
    "Rasta Brown and Green",
    "Rasta Copper and Gold",
    "Rasta Red and Gold",
    "Rasta Red and Silver",
    "Rasta Red and Spectrum",
    "Rasta Red",
    "Brown Beard",
    "Copper Beard",
    "Magenta Beard",
    "Helmet Blue",
    "Helmet Indigo",
  ],
  Joker: [
    "Aqua Punk",
    "Auburn Afro",
    "Auburn Rock",
    "Gold Punk",
    "Bald",
    "Gray Emo ",
    "Black Afro",
    "Indigo Emo",
    "Black Beard",
    "Indigo Rock",
    "Black Brown Afro",
    "Jade Afro",
    "Black Dreadlocks Silver Beads",
    "Light Emo",
    "Black Natural Afro",
    "Maelstrom",
    "Emo Maelstrom",
    "Rock Maelstrom",
    "Black and Brown Afro",
    "Magenta Flame",
    "Blue Emo",
    "Magenta Punk",
    "Blue Flame Mohawk",
    "Maroon Afro",
    "Blue Knot",
    "Mop Top",
    "Blue Low Cut",
    "Neon Emo",
    "Pink Rock",
    "Brown Dreadlocks",
    "Purple Rock",
    "Brown Low Cut",
    "Rasta Gold",
    "Rasta Red",
    "Red Flame Mohawk",
    "Cooper Natural Afro",
    "Red Knot",
    "Copper Dreadlocks",
    "Red Punk",
    "Copper Rock",
    "Red Shadow Punk",
    "Dark Red Punk",
    "Redish Knot",
    "Dark Shag ",
    "Rasta Spectrum",
    "Rasta Black and Gold",
    "Saphire Flame Mohawk",
    "Rasta Auburn and Gold",
    "Rasta Black and Gold",
    "Rasta Black and Silver Beads",
    "Rasta Black and Spectrum",
    "Rasta Brown and  Silver",
    "Rasta Brown and Gold",
    "Rasta Brown and Green",
    "Rasta Copper and Gold",
    "Rasta Red and Gold",
    "Rasta Red and Silver",
    "Rasta Red and Spectrum",
    "Rasta Red",
    "Brown Beard",
    "Copper Beard",
    "Magenta Beard",
    "Helmet Blue",
    "Helmet Indigo",
  ],
  Ninja: [
    "Aqua Punk",
    "Auburn Afro",
    "Auburn Rock",
    "Gold Punk",
    "Bald",
    "Gray Emo ",
    "Black Afro",
    "Indigo Emo",
    "Black Beard",
    "Indigo Rock",
    "Black Brown Afro",
    "Jade Afro",
    "Black Dreadlocks Silver Beads",
    "Light Emo",
    "Black Natural Afro",
    "Black and Brown Afro",
    "Magenta Flame",
    "Blue Emo",
    "Magenta Punk",
    "Blue Flame Mohawk",
    "Maroon Afro",
    "Blue Knot",
    "Mop Top",
    "Blue Low Cut",
    "Neon Emo",
    "Pink Rock",
    "Brown Dreadlocks",
    "Purple Rock",
    "Brown Low Cut",
    "Rasta Gold",
    "Rasta Red",
    "Red Flame Mohawk",
    "Cooper Natural Afro",
    "Red Knot",
    "Copper Dreadlocks",
    "Red Punk",
    "Copper Rock",
    "Red Shadow Punk",
    "Dark Red Punk",
    "Redish Knot",
    "Dark Shag ",
    "Rasta Spectrum",
    "Rasta Black and Gold",
    "Saphire Flame Mohawk",
    "Rasta Auburn and Gold",
    "Rasta Black and Gold",
    "Rasta Black and Silver Beads",
    "Rasta Black and Spectrum",
    "Rasta Brown and  Silver",
    "Rasta Brown and Gold",
    "Rasta Brown and Green",
    "Rasta Copper and Gold",
    "Rasta Red and Gold",
    "Rasta Red and Silver",
    "Rasta Red and Spectrum",
    "Rasta Red",
    "Brown Beard",
    "Copper Beard",
    "Magenta Beard",
    "Rock Jester",
    "Emo Jester",
    "Helmet Blue",
    "Helmet Indigo",
    "Prince of Chaos",
    "The Ace of Knaves",
  ],
  "West Papua Shaman": [
    "Prince of Chaos",
    "The Ace of Knaves",
    "Air Jesters",
    "Helmet Blue",
    "Helmet Indigo",
  ],
  "Ol Glas Shaman": [
    "Prince of Chaos",
    "The Ace of Knaves",
    "Air Jesters",
    "Helmet Blue",
    "Helmet Indigo",
  ],
  "Papua Shaman": [
    "Prince of Chaos",
    "The Ace of Knaves",
    "Air Jesters",
    "Helmet Blue",
    "Helmet Indigo",
  ],
  "Kejawen Shaman": [
    "Prince of Chaos",
    "The Ace of Knaves",
    "Air Jesters",
    "Helmet Blue",
    "Helmet Indigo",
  ],
  "Kebatinan Shaman": [
    "Prince of Chaos",
    "The Ace of Knaves",
    "Air Jesters",
    "Helmet Blue",
    "Helmet Indigo",
  ],
  "Aqua Punk": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Auburn Afro": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Auburn Rock": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Gold Punk": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  Bald: [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Gray Emo ": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Black Afro": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Indigo Emo": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Black Beard": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Brown Beard": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Copper Beard": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Magenta Beard": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Indigo Rock": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Black Brown Afro": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Jade Afro": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Black Dreadlocks Silver Beads": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Light Emo": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Black Natural Afro": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Black and Brown Afro": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Magenta Flame": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Blue Emo": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Magenta Punk": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Blue Flame Mohawk": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Maroon Afro": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Blue Knot": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Mop Top": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Blue Low Cut": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Neon Emo": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Rasta Spectrum": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Pink Rock": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Brown Dreadlocks": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Purple Rock": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Brown Low Cut": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Rasta Gold": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Rasta Red": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Brown and Green Rasta Black and Gold": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Red Dreadlocks Silver Beads": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Brown and Green Dreadlocks Silver Beads": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Red Flame Mohawk": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Cooper Natural Afro": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Red Knot": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Copper Dreadlocks": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Red Punk": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Copper Rock": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Red Shadow Punk": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Dark Red Punk": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Redish Knot": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Dark Shag ": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Rasta Spectrum": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Rasta Black and Gold": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Saphire Flame Mohawk": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  Maelstrom: [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Emo Maelstrom": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Rock Maelstrom": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Emo Jester": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "Rock Jester": [
    "Helmet Blue",
    "Helmet Indigo",
    "Ruby Wizard Hat",
    "Sapphire Wizard Hat",
    "The Ace of Knaves",
    "Prince of Chaos",
  ],
  "BTC Pendant": ["Brown Beard", "Copper Beard", "Magenta Beard"],
  Beaded: ["Brown Beard", "Copper Beard", "Magenta Beard"],
  "ETH Pendant": ["Brown Beard", "Copper Beard", "Magenta Beard"],
  Emerald: ["Brown Beard", "Copper Beard", "Magenta Beard"],
  "Gold Link": ["Brown Beard", "Copper Beard", "Magenta Beard"],
  "Jade Pendant": ["Brown Beard", "Copper Beard", "Magenta Beard"],
  "Platinum Link": ["Brown Beard", "Copper Beard", "Magenta Beard"],
  Spiked: ["Brown Beard", "Copper Beard", "Magenta Beard"],
  "Onyx Link": ["Brown Beard", "Copper Beard", "Magenta Beard"],
};

/**
 * Require combinations of files when constructing DNA, this bypasses the
 * randomization and weights.
 *
 * The layer order matters here, the key (left side) is an item within
 * the layer that comes first in the stack.
 * the items in the array are "required" items that should be pulled from folders
 * further in the stack
 */
const forcedCombinations = {
  "West Papua Shaman": ["Bald", "Blangkon", "Indigenous"],
  "Ol Glas Shaman": ["Bald", "Blangkon", "Indigenous"],
  "Papua Shaman": ["Bald", "Blangkon", "Indigenous"],
  "Kebatinan Shaman": ["Bald"],
  "Kejawen Shaman": ["Bald"],
  Jester: ["The Ace of Knaves", "Focused", "Air Jesters"],
  Joker: ["Prince of Chaos", "Focused", "Air Jokers"],
  "Space Blue": ["Helmet Blue"],
  "Space Indigo": ["Helmet Indigo"],
  "Helmet Blue": ["Space Blue"],
  "Helmet Indigo": ["Space Indigo"],
  "Indigo Wizard Hat": ["Indigo Formal"],
  "Ruby Wizard Hat": ["Ruby Formal"],
  "Sapphire Wizard Hat": ["Sapphire Formal"],
};

const shuffleLayerConfigurations = false;

/**
 * In the event that a filename cannot be the trait value name, for example when
 * multiple items should have the same value, specify
 * clean-filename: trait-value override pairs. Wrap filenames with spaces in quotes.
 */
const traitValueOverrides = {
  /*
  Helmet: "Space Helmet",
  "gold chain": "GOLDEN NECKLACE",*/
};

const debugLogs = false;

const format = {
  width: 2800,
  height: 2800,
};

const background = {
  generate: false,
  brightness: "80%",
};

const extraMetadata = {};

const extraAttributes = () => [
  // Optionally, if you need to overwrite one of your layers attributes.
  // You can include the same name as the layer, here, and it will overwrite
  //
  // {
  // trait_type: "Bottom lid",
  //   value: ` Bottom lid # ${Math.random() * 100}`,
  // },
  // {
  //   display_type: "boost_number",
  //   trait_type: "Aqua Power",
  //   value: Math.random() * 100,
  // },
  // {
  //   display_type: "boost_number",
  //   trait_type: "Health",
  //   value: Math.random() * 100,
  // },
  // {
  //   display_type: "boost_number",
  //   trait_type: "Mana",
  //   value: Math.floor(Math.random() * 100),
  // },
];

const rarityDelimiter = "#";

const uniqueDnaTorrance = 10000;

/**
 * Set to true to always use the root folder as trait_tybe
 * Set to false to use weighted parent folders as trait_type
 * Default is true.
 */
const useRootTraitType = true;

const preview = {
  thumbPerRow: 5,
  thumbWidth: 50,
  imageRatio: format.width / format.height,
  imageName: "preview.png",
};

module.exports = {
  background,
  baseUri,
  buildDir,
  debugLogs,
  description,
  emptyLayerName,
  extraAttributes,
  extraMetadata,
  forcedCombinations,
  format,
  hashImages,
  incompatible,
  layerConfigurations,
  layersDir,
  outputJPEG,
  preview,
  rarityDelimiter,
  shuffleLayerConfigurations,
  startIndex,
  traitValueOverrides,
  uniqueDnaTorrance,
  useRootTraitType,
};
